"""Repository interfaces the application layer depends on. Persistence only -
no matching, scoring, email or archive rules behind these."""
from __future__ import annotations

from datetime import date, datetime
from typing import Protocol

from backend.domain.models import (
    Job, JobChangeRecord, JobEvaluation, JobSource, PostingHistory, ScrapeRun, ScraperRun, SourceIdentity,
)


class JobRepository(Protocol):
    def get(self, job_id: int) -> Job: ...
    def save(self, job: Job) -> Job: ...
    def list_matchable(self) -> list[Job]: ...
    def delete_many(self, job_ids: list[int]) -> None: ...


class JobSourceRepository(Protocol):
    def find_by_identity(self, identity: SourceIdentity) -> JobSource | None: ...
    def save(self, source: JobSource) -> JobSource: ...
    def list_for_job(self, job_id: int) -> list[JobSource]: ...
    def list_unseen_in_run(self, recruitment_company: str, run_id: str) -> list[JobSource]: ...
    def job_ids_for_company(self, recruitment_company: str) -> set[int]: ...
    def count_for_company(self, recruitment_company: str) -> int: ...
    def delete_many(self, source_ids: list[int]) -> None: ...


class ScrapeRunRepository(Protocol):
    def save(self, run: ScrapeRun) -> ScrapeRun: ...


class ScraperRunRepository(Protocol):
    def save(self, scraper_run: ScraperRun) -> ScraperRun: ...

class JobEvaluationRepository(Protocol):
    def add(self, evaluation: JobEvaluation) -> None: ...
    def delete_superseded(self, run_id: str) -> None: ...


class JobChangeRepository(Protocol):
    def add(self, change: JobChangeRecord) -> None: ...
    def list_for_run(self, run_id: str) -> list[JobChangeRecord]: ...


class PostingHistoryRepository(Protocol):
    def find(self, company: str, key: str) -> PostingHistory | None: ...
    def find_gone_by_title(self, company: str, title_key: str) -> PostingHistory | None: ...
    def save(self, history: PostingHistory) -> PostingHistory: ...
    def delete(self, history_id: int) -> None: ...
    def mark_gone(self, company: str, keys: list[str], now: datetime) -> None: ...


class NotificationRepository(Protocol):
    def try_claim(self, notification_type: str, scheduled_date: date, recipient: str,
                  run_id: str | None, now: datetime, stale_before: datetime) -> bool: ...
    def mark_sent(self, notification_type: str, scheduled_date: date, recipient: str, now: datetime) -> None: ...
    def release(self, notification_type: str, scheduled_date: date, recipient: str) -> None: ...


class UnitOfWork(Protocol):
    jobs: JobRepository
    sources: JobSourceRepository
    runs: ScrapeRunRepository
    scraper_runs: ScraperRunRepository
    evaluations: JobEvaluationRepository
    changes: JobChangeRepository
    history: PostingHistoryRepository

    def commit(self) -> None: ...
